In [5]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

dataset=load_digits()

X, y=dataset.data, dataset.target
 
y_binary_imbalanced =y.copy() #copy data without link address
y_binary_imbalanced[y_binary_imbalanced !=1]=0

X_train, X_test, y_train, y_test =train_test_split(X,y_binary_imbalanced,random_state=0)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

lr=LogisticRegression(solver='liblinear').fit(X_train,y_train)
y_logistic_pred=lr.predict(X_test)
confusion_logistic=confusion_matrix(y_logistic_pred,y_test)

print('Confusion matrix for logistic regression:\n',confusion_logistic)

Confusion matrix for logistic regression:
 [[401   6]
 [  6  37]]


In [25]:
from sklearn.svm import SVC

svm=SVC(kernel='rbf',C=1).fit(X_train,y_train)
y_svm_pred=svm.predict(X_test)
confusion_svm=confusion_matrix(y_svm_pred,y_test)

print('Confusion matrix for svm:\n',confusion_svm)

Confusion matrix for svm:
 [[407   2]
 [  0  41]]


#### Evaluation metrics

In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
#Accuracy=(TP+TN)/(TP+TN+FP+FN)
#Precision=TP/(TP+FP)
#Recall=TP/(TP+FN)
#F1=2*Precision*Recall/(Precision+Recall)

print('---Logistic---')
print('Confusion matrix:\n',confusion_logistic)
print('Accuracy:{:.2f}'.format(accuracy_score(y_test,y_logistic_pred)))
print('Precision:{:.2f}'.format(precision_score(y_test,y_logistic_pred)))
print('Recall:{:.2f}'.format(recall_score(y_test,y_logistic_pred)))
print('F1:{:.2f}'.format(f1_score(y_test,y_logistic_pred)))




---Logistic---
Confusion matrix:
 [[401   6]
 [  6  37]]
Accuracy:0.97
Precision:0.86
Recall:0.86
F1:0.86


In [29]:
print('---svm---')
print('Confusion matrix:\n',confusion_svm)
print('Accuracy:{:.2f}'.format(accuracy_score(y_test,y_svm_pred)))
print('Precision:{:.2f}'.format(precision_score(y_test,y_svm_pred)))
print('Recall:{:.2f}'.format(recall_score(y_test,y_svm_pred)))
print('F1:{:.2f}'.format(f1_score(y_test,y_svm_pred)))

---svm---
Confusion matrix:
 [[407   2]
 [  0  41]]
Accuracy:1.00
Precision:1.00
Recall:0.95
F1:0.98


In [32]:
from sklearn.metrics import classification_report
print('---logistic---')
print(classification_report(y_test,y_logistic_pred,target_names=['not 1','1']))
print('---svm---')
print(classification_report(y_test,y_svm_pred,target_names=['not 1','1']))


---logistic---
              precision    recall  f1-score   support

       not 1       0.99      0.99      0.99       407
           1       0.86      0.86      0.86        43

    accuracy                           0.97       450
   macro avg       0.92      0.92      0.92       450
weighted avg       0.97      0.97      0.97       450

---svm---
              precision    recall  f1-score   support

       not 1       1.00      1.00      1.00       407
           1       1.00      0.95      0.98        43

    accuracy                           1.00       450
   macro avg       1.00      0.98      0.99       450
weighted avg       1.00      1.00      1.00       450

